

-- Q1.	Write a query to display the first name, last name, and rental date of all customers who rented a film. 
-- Use the customer and rental tables.
use sakila;
show tables;
select * from customer;
select * from rental;

select c.first_name, c.last_name, r.rental_date 
from customer c
left join rental r
on c.customer_id = r.customer_id;



-- Q2.	Write a query to display the first name, last name, and address of all customers whose district is either Alberta or Texas.
-- Use the customer and address tables.

select c.first_name , c.last_name , a.address ,a.district
from customer c
join address a
on c.address_id = a.address_id
where a.district IN ("Alberta","Texas") ;

select * from address;




-- Q3.List all films along with their category names, including films that may not belong to any category. 
-- Then sort it by category names. Use the film, film_category and category tables.

select * from film;
select * from film_category;
select * from category;

select a.title as film_title, c.name as film_category
from film a
left join film_category b
on a.film_id = b.film_id
left join category c
on b.category_id = c.category_id
order by film_category ;




-- Q4.Display the number of rentals per store. Use the rental, inventory, and store tables.

select * from rental;
select * from inventory;
select * from store;

select c.store_id,count(a.rental_id) as no_of_rentals
from rental a 
join inventory b 
on a.inventory_id = b.inventory_id
join store c
on b.store_id = c.store_id
group by c.store_id;




-- Q5.	List the names of categories that have more than 50 films. Use table category and film_category.

select * from category;
select * from film_category;

select  c.name , count(f.film_id) as no_of_films
from category c
join film_category f 
on c.category_id = f.category_id
group by c.category_id
having no_of_films >50;





-- Q6.	Write a query to display the film titles that have been rented by the customer named 'Mary Smith'.
--  Use a subquery to get the customer ID.

select c.first_name , c.last_name,f.title 
from film f
join inventory i
on f.film_id = i.film_id
join rental r
on r.inventory_id = i.inventory_id
join customer c
on c.customer_id = r.customer_id
where r.customer_id = (
select customer_id from customer where first_name = "MARY" and last_name = "SMITH" 
);






-- Q7.	Write a query to display the total rental income generated by each film. Use film, inventory, rental and payment tables.

select * from payment;
select * from inventory;
select * from film;
select * from rental;

select f.title , sum(p.amount) as total_amount
from film f
join inventory i
on f.film_id = i.film_id
join rental r
on r.inventory_id = i.inventory_id
join payment p 
on p.rental_id = r.rental_id
group by f.title
order by total_amount desc;






-- Q8.	Write a query to display the total number of films each actor has acted in. Use actor, film_Actor tables.

select * from actor;
select * from film_actor;

select concat(a.first_name ," ", a.last_name) as full_name , count(f.film_id) as no_of_films
from actor a
join film_actor f
on a.actor_id = f.actor_id
group by a.actor_id
order by no_of_films desc;







-- Q9.	Write a query to list all rentals with a case statement that displays 'New Customer' if the customer_id is greater than 300, and 'Regular Customer' otherwise. 
-- Use table rental.

select * from rental;

select *,
case when customer_id > 300 then "New Customer"
else "Regular Customer"
end as customer_type
from rental;







-- Q10.	Write a query to find all films with titles that start with the letter 'A'. Display the film title and the release year.
--  Use film table and  inventory table.

select * from film;
select * from inventory;


select distinct f.title,f.release_year 
from film f
join inventory i 
on f.film_id = i.film_id
where title like "A%";



-- Q11. Create a new DB and perform below operations using SQL commands.
create database school_record;
use school_record;

-- (a)	Create a table with 2 columns – Student_ID, Marks
create table student_record(
Student_ID int , Marks int);
show tables;

-- (b)	Insert 2 records in this table.
insert into student_record values
(1,99),
(2,96);
select * from student_record;

-- (c)	Rename the Marks column with Score.
alter table student_record 
change column Marks Score int;

-- (d)	Then delete the table.
drop table student_record ;

-- (e)	Then delete the Database.
drop database school_record;

